---

#- name: Copy /etc/network/interfaces file
  #sudo: yes
  #copy:
    #src=network/interfaces
    #dest=/etc/network/interfaces
    #owner=root
    #group=root


- name: Change jetson board exposed hostname
  sudo: yes
  shell: sed -i 's/127.0.1.1 tegra-ubuntu/127.0.1.1 jetson-tk1/' /etc/hosts && echo {{hostname}} > /etc/hostname
