---

- name: Extra distribution repositories [multiverse, universe]
  become: yes
  become_user: root
  shell: apt-add-repository multiverse && apt-add-repository universe
  register: installPkgs


- name: Install basic tools
  when: installPkgs|success
  become: yes
  become_user: root
  apt:  pkg={{ item }}
        update_cache=yes
        state=latest
  with_items:
    - vim
    - git
    - zsh # \m/
    - curl
    - wget


- name: Install dev-utils
  when: installPkgs|success
  become: yes
  become_user: root
  apt:  pkg={{ item }}
        update_cache=yes
        state=latest
  with_items:
    - build-essential
    - python-dev
    - make
    - cmake
    - cmake-curses-gui
    #- mesa-utils

