---

- name: Preparing system for max Performance configuration
  sudo: yes
  file: path=/usr/local/postFlash
        state=directory
        recurse=yes
        owner=root
        group=root
  register: dirExist


- name: Configuring for maxPerformance (Step-1)
  when: dirExist|success
  sudo: yes
  copy: src=scripts/maxPerformance.sh
        dest=/usr/local/postFlash/maxPerformance.sh
        owner=root
        group=root
        mode="u=rwx"
  register: scriptExist


- name: Configuring for maxPerformance (Step-2)
  when: scriptExist|success
  sudo: yes
  copy: src=rc.local
        dest=/etc/rc.local
        owner=root
        group=root


- name: Disable USB Autosuspend Mode [Step-1]
  sudo: no
  become: yes
  become_user: klpanagi
  copy: src=scripts/disable_usb_autosuspend.sh
        dest=~/
        owner=klpanagi
        group=klpanagi
  register: suspExec


- name: Disable USB Autosuspend Mode [Step-2]
  when: suspExec|success
  sudo: yes
  shell: bash /home/klpanagi/disable_usb_autosuspend.sh && rm -rf /home/klpanagi/disable_usb_autosuspend.sh


- name: Enable USB 3.0 Support [Step-2]
  sudo: yes
  shell: sed -i 's/usb_port_owner_info=0/usb_port_owner_info=2/' /boot/extlinux/extlinux.conf


- name: Setting boot environment
  sudo: yes
  copy: src=env/environment
        dest=/etc/
        owner=root
        group=root

- name: Change jetson HostName
  sudo: yes
  shell: sed -i 's/127.0.1.1 tegra-ubuntu/127.0.1.1 jetson-tk1/' /etc/hosts && echo {{hostname}} > /etc/hostname
