---

- name: Create user cyanms
  become: yes
  become_user: root
  user: name={{admin_username}}
        password={{admin_password}}
        shell=/bin/bash
        groups=sudo,dialout,video,audio,adm
        append=yes
        createhome=yes
  register: userExist


#- name: Create scripts directory
  #when: userExist|success
  #become: yes
  #become_user: ubuntu
  #become_method: sudo
  #file: path=/home/klpanagi/scripts
        #state=directory
        #recurse=yes
        #owner=klpanagi
        #group=klpanagi
  #register: scriptdirexist


#- name: Transfer system_info script
  #when: scriptdirexist|success
  #become: yes
  #become_user: ubuntu
  #become_method: sudo
  #copy:
    #src=scripts/system_info.sh
    #dest=/home/klpanagi/scripts/system_info.sh
    #owner=klpanagi
    #group=klpanagi
    #mode="u=rwx"

#- name: Copy tegrastats bin at klpanagi user space
  #when: scriptdirexist|success
  #sudo: yes
  #file:
    #path=/home/klpanagi/tegrastats
    #state=file
    #owner=klpanagi
    #group=klpanagi
    #mode="u=wrx"
