---

hostname: "jetson-tk1"

admin_username: "cyanms"
admin_password: "$6$rounds=656000$FI8gLqqHbXxqdqtI$g5fiKHrwl1UoSa.Q4GmJy.jgBIHDLKWydyxdKk1tp4qBLaYVGqwlAp3eISVQeMFfbakpvWO8Y/L/mY54k0et51"

default_user: "ubuntu"
default_user_pass: "$6$rounds=656000$mR04VHYMipvL1M1K$iL7ImocKti2ZZKUXo.u.6YF9Mp.AMIAvI3f223OtireeMMSBcpLHSUTDYJAto39n8uuHh.ZGZrly.bnKUXht0."
